# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sang9
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: email-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: email-service

provider:
  name: aws
  runtime: nodejs20.x

plugins:
  - serverless-offline
functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - httpApi:
          path: send-email
          method: post
